defaults: &defaults
  twitter:
    consumer_key:    <%= ENV['TWITTER_CONSUMER_KEY']    || 'YOUR_TWITTER_CONSUMER_KEY' %>
    consumer_secret: <%= ENV['TWITTER_CONSUMER_SECRET'] || 'YOUR_TWITTER_CONSUMER_SECRET' %>
development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
