@App =
  Bootstraps:  {}
  Routers:     {}
  Views:       {}
  Models:      {}
  Collections: {}
  Templates:   {}
  Services:    {}
  routers:     {}
  views:       {}
  models:      {}
  collections: {}
